#!/bin/bash
echo "Running pre-push hook"
current_dir=$(pwd)
echo "Current directory is $current_dir"

while read local_ref local_sha remote_ref remote_sha; do
    branch_name=$(echo "$local_ref" | sed 's/refs\/heads\///')
done

if [ "$branch_name" = "main" ]; then
    echo "Pushing to main branch with normal push is not allowed!"
    echo "Please use the command \`npm run release\` to push changes!!"
    exit 1
elif [ "$branch_name" = "" ]; then
    echo "No changes pushed"
else
    echo "branch_name is not main"
fi
exit 0
