#!/bin/bash
echo "Running pre-push hook"
current_dir=$(pwd)
echo "Current directory is $current_dir"

while read local_ref local_sha remote_ref remote_sha; do
    branch_name=$(echo "$local_ref" | sed 's/refs\/heads\///')
done

if [ "$branch_name" = "main" ]; then
    echo "branch_name is $branch_name"
    latest_tag=$(git describe --tags --abbrev=0)
    commit_count_since_latest_tag=$(git rev-list $latest_tag..HEAD --count)
    if [ commit_count_since_latest_tag -eq 0 ]; then
        echo "No new commits since latest tag"
        exit 0
    else
        echo "New commits since latest tag"
        node ./scripts/gitVersion.ts
        exit 1
    fi
elif [ "$branch_name" = "" ]; then
    echo "No changes pushed"
else
    echo "branch_name is not main"
fi
exit 0
