#!/bin/sh
while read local_ref local_sha remote_ref remote_sha; do
    branch_name=$(echo "$local_ref" | sed 's/refs\/heads\///')
done

if [ "$branch_name" = "main" ]; then
    echo "branch_name is $branch_name"
fi
